<?xml version="1.0"?>
<!DOCTYPE empresas [
    <!ELEMENT empresas (empresa)?>
    <!ELEMENT empresa (propietario*,jefe?,empleado+)>
    <!ELEMENT propietario (codigo*,nombre*,tfno*,edad?)>
    <!ELEMENT jefe (codigo*,nombre*,tfno*,edad?)>
    <!ELEMENT empleado (codigo*,nombre*,tfno*,edad?)>
    <!ELEMENT codigo EMPTY>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tfno (#PCDATA)>
    <!ATTLIST codigo dpto CDATA #IMPLIED>
    <!ATTLIST codigo puesto CDATA #IMPLIED>
    <!ELEMENT edad (#PCDATA)>
    <!ENTITY manuel "entity-value">
    <!ENTITY jorge "entity-value">
]>
<empresas>
  <empresa>
    <propietario>
      <codigo />
      <nombre>&manuel;</nombre>
      <tfno>6258555</tfno>
    </propietario>
    <jefe>
      <codigo />
      <nombre>&jorge;</nombre>
      <tfno>6258555</tfno>
    </jefe>
    <empleado>
      <codigo dpto="3" puesto="entrenador_personal" />
      <nombre>&jorge;</nombre>
      <tfno>6258555</tfno>
      <edad>45</edad>
    </empleado>
    <empleado>
      <codigo />
      <nombre>&jorge;</nombre>
      <tfno>6258555</tfno>
      <edad>45</edad>
    </empleado>
  </empresa>
</empresas>